#!/usr/bin/env python3

import os
import sys
import shutil

from utils import checkDotGripExist, addFileToIndex
directory = '.grip'
index = '.grip/.index'


def main():
    checkDotGripExist()
    if len(sys.argv) == 1:
        print("usage: grip-add <filenames>", file=sys.stderr)

    for file in sys.argv[1:]:
        filePath = os.path.join(os.getcwd(), f"{file}")
        if not os.path.exists(filePath) and os.path.exists(os.path.join(index,file)):
             # ??? remove file from index
             os.remove(os.path.join(index, file))
             return
        elif not os.path.exists(filePath):
            print(f"grip-add: error: can not open '{file}'", file=sys.stderr)
            sys.exit(1)
        
        addFileToIndex(filePath)

if __name__ == "__main__":
        main()