#!/usr/bin/env python3

import os
import sys
directory = '.grip'

if not os.path.exists(directory):
    os.mkdir(directory)
    indexDir = (os.path.join(directory,'.index'))
    commitsDir = (os.path.join(directory,'.commits'))
    os.mkdir(indexDir)
    os.mkdir(commitsDir)
    print('Initialized empty grip repository in .grip')
else:
    print('grip-init: error: .grip already exists',file=sys.stderr)
    sys.exit(1)