#!/usr/bin/env python3

import os
import sys
from utils import isDirectoryEmpty, copyIndexToCommit, getCurrCommitNum, copyPreviousCommit, updateCommitTracker, updateLog, createLog, checkNothingToCommit

commitsDir = '.grip/.commits'
firstCommit = os.path.join(commitsDir, '0')
message = sys.argv[2]

if isDirectoryEmpty(commitsDir):
    os.mkdir(firstCommit)
    with open('.grip/.commits/commitTracker', 'w') as file:
        file.write("0")
    copyIndexToCommit(0)
    print("Committed as commit 0")
    updateCommitTracker(0)
    createLog(message)
else:
    currCommit = getCurrCommitNum()
    nextCommit = currCommit + 1
    successiveCommitDir = os.path.join(commitsDir, str(f'{nextCommit}'))
    os.mkdir(successiveCommitDir)
    checkNothingToCommit()
    if currCommit != 0:
        copyPreviousCommit(currCommit)
    copyIndexToCommit(nextCommit)
    print(f"Committed as commit {nextCommit}")
    updateCommitTracker(nextCommit)
    updateLog(nextCommit, message)